### ISSUE TITLE
Unrepresentable Size

### ISSUE THREAD

**Issue by vhmth** [legokichi/ts-ebml#1]
It seems like you are using `node-ebml` to get the size of the content of a tag:

https://github.com/legokichi/ts-ebml/blob/master/src/EBMLDecoder.ts#L133

I explained in my video at the bottom of this issue why that won't work:

https://github.com/themasch/node-ebml/issues/8

How would we properly solve this issue? I'm game to help you out, but figured you may have some more guidance

**Comment by legokichi** [comment]
At first I tried to write the code as below but it has become troublesome.

```typescript
const _readVint: (buffer: Buffer, start: number)=> null | ({length: number; value: number; }) = require("ebml/lib/ebml/tools").readVint;
export function readVint(buffer: Buffer, start: number): null | ({length: number; value: number; }) | ({length: 8; value: -1 | Uint64BE }){
  const a = _readVint(buffer, start);
  if(a === null){ return a; }
  const {length, value} = a;
  if(length === 8 && value === -1){
    const buf = buffer.slice(0, 8);
    const val64 = new Uint64BE(buf);
    if(val64.toString(2) === "111111111111111111111111111111111111111111111111111111111"){
      // unknown size
      return {length, value};
    }else{
      return {length: <8>length, value: val64};
    }
  }
  return a;
}
```

In conclusion, let's emscripten these libraries.

https://github.com/Matroska-Org/libebml/
https://github.com/mozilla/gecko-dev/tree/master/dom/media/webm
https://chromium.googlesource.com/webm/libvpx/+/master/third_party/libwebm
