### ISSUE TITLE
No reader.cues and reader.duration for audio-only webm files

### ISSUE THREAD

**Issue by lepinsk** [legokichi/ts-ebml#13]
In testing ```example_seekable.ts``` it seems that switching from audio & video to audio-only files causes the library to fail to generate cues or a duration value for files (both for the ```main_from_file``` and ```main_from_recorder``` tests).

You can verify this by modifying ```main_from_recorder``` to call ```getUserMedia``` with ```video: false``` (and a couple of other changes to indicate the proper mime type & audio tags). ```reader.duration``` seems to be 0 in all cases where the file is audio-only.

**Comment by legokichi** [comment]
@lepinsk fix it. try v2.0.1

**Comment by lepinsk** [comment]
@legokichi – thanks! Looks like that resolved it.

One question: in ```example_seekable``` with ```?type=recorder``` and some ```timeSlice``` start value for the MediaRecorder, is ```reader``` storing  copy of the entire media file, or just collecting metadata about the file? In other words, if you ran the example for an hour and generated a large video file, would this file be stored in memory twice (inside the ```webM``` variable as well as ```reader```) or just inside ```webM```?

**Comment by legokichi** [comment]
@lepinsk EBMLReader hold an arraybuffer of webm metadata. In addition to this, temporarily hold the arraybuffer to emit each cluster element comes.
