### ISSUE TITLE
date field is not converted

### ISSUE THREAD

**Issue by publicocean0** [legokichi/ts-ebml#6]

**Comment by legokichi** [comment]
in [spec](https://www.matroska.org/technical/specs/index.html)

```
Date - signed 8 octets integer in nanoseconds with 0 indicating the precise beginning of the millennium (at 2001-01-01T00:00:00,000000000 UTC)
```

It's means that Date is represented by int64 and nanoseconds.
But JavaScript number is float64 and Date is milliseconds.
Therefore, we have to use the string int64.

if you need Date Object, please see the following [conversion code](https://github.com/legokichi/ts-ebml/blob/master/src/test.ts#L46)

**Comment by publicocean0** [comment]
thank you so much.... i got crazy for the conversion and it was still instable :)
